lib/knowhere_cafe_web/router.ex
defmodule KnowhereCafeWeb.Router do
  use KnowhereCafeWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowInvitation]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {KnowhereCafeWeb.LayoutView, :not_auth}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler

    plug :put_layout, {KnowhereCafeWeb.LayoutView, :app}
  end

  scope "/" do
    pipe_through :browser

    # Session only (no registration) and extension routes for Pow
    pow_session_routes()
    pow_extension_routes()
  end

  scope "/", KnowhereCafeWeb do
    pipe_through :browser

    get "/about", PageController, :about
  end

  scope "/", Pow.Phoenix, as: "pow" do
    # Registration was disabled so pow_routes() was replaced with
    # pow_session_routes() which means that this is needed to handle the routes.
    pipe_through [:browser, :protected]

    resources "/registration", RegistrationController,
      singleton: true,
      only: [:edit, :update]
  end

  scope "/", KnowhereCafeWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index

    resources "/statuses", StatusController, except: [:new, :update, :edit, :delete]
    resources "/posts", PostController, except: [:update, :edit, :delete]
    resources "/tags", TagController, except: [:new, :update, :edit, :delete]

    post "/statuses/:status_id/thanks/", ThanksController, :create_status_thanks
    post "/posts/:post_id/thanks", ThanksController, :create_post_thanks
    post "/comments/:comment_id/thanks", ThanksController, :create_comment_thanks

    post "/posts/:post_id/comment", CommentController, :create

    get "/users", UserController, :index
    get "/users/:id", UserController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", KnowhereCafeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: KnowhereCafeWeb.Telemetry
    end
  end
end

lib/knowhere_cafe/users.ex
defmodule KnowhereCafe.Users do
  @moduledoc """
  The users context.

  This module is deeply related to the Pow authentication system that Knowhere
  is built with and acts as the Context for that as well.
  """

  alias KnowhereCafe.Repo
  alias KnowhereCafe.Users.User
  use Pow.Ecto.Context,
    repo: KnowhereCafe.Repo,
    user: KnowhereCafe.Users.User

  @doc """
  Returns a list of all users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user(123)
      %User{}

      iex> get_user(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id) do
    User
    |> Repo.get!(id)
    |> Repo.preload([
      :invited_by,
      :invited_users,
      :tags,
      posts: [:user],
      statuses: [:user]
    ])
  end

  @doc """
  Gets the root user with ID 1 that was not invited by another user.
  Used to traverse the invitation tree.

  Raises `Ecto.NoResultsError` if the root User does not exist.

  ## Examples

      iex> get_root_user()
      %User{}

  """
  def get_root_user! do
    User
    |> Repo.get!(1)
    |> Repo.preload(:invited_users)
  end

  @doc """
  Gets the users invited by the given user.
  This is largely an wrapper to `Repo.preload(user, :invited_users)`
  but keeps the business logic in this module.

  ## Examples

      iex> get_invited_users(%User{})
      [%User{}, ...]

  """
  def get_invited_users(%User{} = user) do
    Repo.preload(user, :invited_users).invited_users
  end

  # ===========================
  # Pow Callbacks and functions
  # ===========================

  # Overrides the way Pow gets the user to allow for preloading
  @impl true
  def get_by(clauses) do
    clauses
    |> pow_get_by()
    |> preload_profile()
  end

  @impl true
  def create(params), do: pow_create(params)

  @impl true
  def authenticate(params) do
    params
    |> pow_authenticate()
    |> preload_profile()
  end

  @impl true
  def update(user, params), do: pow_update(user, params)

  @impl true
  def delete(user), do: pow_delete(user)

  defp preload_profile(nil), do: nil
  defp preload_profile(user) do
    Repo.preload(user, :tags)
  end
end

lib/knowhere_cafe/users/user.ex
defmodule KnowhereCafe.Users.User do
  use Ecto.Schema
  import Ecto.Changeset

  use Pow.Ecto.Schema,
    user_id_field: :username

  use Pow.Extension.Ecto.Schema,
    extensions: [PowInvitation]

  alias KnowhereCafe.Statuses.Status
  alias KnowhereCafe.Posts.Post
  alias KnowhereCafe.Tags

  schema "users" do
    pow_user_fields()

    field :aliases, {:array, :string}
    field :avatar, :string
    field :background, :string
    field :bio, :string

    has_many :statuses, Status
    has_many :posts, Post
    many_to_many :tags, Tags.Tag, join_through: "users_tags", unique: true, on_replace: :delete

    timestamps()
  end

  def changeset(%Ecto.Changeset{} = changeset, attrs) do
    changeset
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
    |> validate_length(:username, max: 20)
  end

  def changeset(%KnowhereCafe.Users.User{} = user, attrs) do
    user
    |> KnowhereCafe.Repo.preload(:tags)
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
    |> cast(attrs, [:avatar, :background, :aliases, :bio])
    |> put_assoc(:tags, Tags.get_many_tags(attrs["tags_ids"]))
    |> validate_length(:username, max: 20)
  end
end

lib/knowhere_cafe_web/controllers/user_controller.ex
defmodule KnowhereCafeWeb.UserController do
  use KnowhereCafeWeb, :controller

  alias KnowhereCafe.Users

  def index(conn, _params) do
    render(conn, "index.html", root_user: Users.get_root_user!())
  end

  def show(conn, %{"id" => id}) do
    case id do
      "me" ->
        redirect(conn, to: Routes.user_path(conn, :show, conn.assigns.current_user.id))

      _ ->
        render(conn, "show.html",
          user: Users.get_user!(id),
          current: id == "#{conn.assigns.current_user.id}"
        )
    end
  end
end

lib/knowhere_cafe_web/views/user_view.ex
defmodule KnowhereCafeWeb.UserView do
  use KnowhereCafeWeb, :view
end

lib/knowhere_cafe_web/templates/user/index.html.eex
<section class="col col-60 card" data-title="Users">
  <div>
    <%= link "Invite Someone", to: Routes.pow_invitation_invitation_path(@conn, :new), class: "btn" %>
    <%= link "View Yourself", to: Routes.user_path(@conn, :show, "me"), class: "btn" %>
  </div>

  <div>
    <%= render "plate.html", conn: @conn, user: @root_user %>
    <div>
      <%= for u <- @root_user.invited_users do %>
        <%# WARNING RECURSION %>
        <%= render "invited_users_list.html", conn: @conn, user: u %>
      <% end %>
    </div>
  </div>
</section>

lib/knowhere_cafe_web/templates/user/invited_users_list.html.eex
<div style="margin-left: 2rem;">
  <%= render "plate.html", assigns %>
  <div>
    <%= for u <- KnowhereCafe.Users.get_invited_users(@user) do %>
      <%= render "invited_users_list.html", conn: @conn, user: u %>
    <% end %>
  </div>
</div>

lib/knowhere_cafe_web/templates/user/plate.html.eex
<a class="card plate" href="<%= Routes.user_path(@conn, :show, @user.id) %>">
  <img src="<%= @user.avatar || Routes.static_path(@conn, "/images/user.svg") %>" class="avatar" style="display: inline-block;">
  <%= @user.username %>
</a>

lib/knowhere_cafe_web/templates/user/show.html.eex
<article class="col col-60">
  <img src="<%= @user.background %>" class="background" />

  <img src="<%= @user.avatar || Routes.static_path(@conn, "/images/user.svg") %>" class="avatar big" />

  <%= if @current do %>
    <section class="card" data-title="Edit">
      Wait a minute... this user is you!
        <%= link "Edit Profile", to: Routes.pow_registration_path(@conn, :edit) , class: "btn" %>
    </section>
  <% end %>

  <section class="card" data-title="User">
    <h1><%= @user.username %></h1>
    <%= if @user.invited_by do %>
      <div>
        Invited by <%= link @user.invited_by.username, to: Routes.user_path(@conn, :show, @user.invited_by.id) %>
        at <%= @user.inserted_at %>.
        <%= if @user.invitation_accepted_at do %>
          Joined at <%= @user.invitation_accepted_at %>
        <% else %>
          They have not joined yet.
        <% end %>
      </div>
    <% else %>
      <p>This user is the site owner, they weren't invited by anyone.</p>
    <% end %>

    <div>
      <strong>Tags:</strong>
      <%= if length(@user.tags) > 0 do %>
        <%= for tag <- @user.tags do %>
          <%= link tag.name, to: Routes.tag_path(@conn, :show, tag.id), class: "chip", style: "background-color: #{tag.color};" %>
        <% end %>
      <% end %>
    </div>
  </section>

  <%= if @user.bio do %>
    <section class="card" data-title="Bio">
      <%= render_markdown @user.bio %>
    </section>
  <% end %>

  <%= if @user.aliases && length(@user.aliases) > 0 do %>
    <section class="card" data-title="Aliases">
      <p>This user also goes by...</p>
      <ul>
      <%= for alias <- @user.aliases do %>
        <li><%= alias %></li>
      <% end %>
      </ul>
    </section>
  <% end %>

  <section class="card" data-title="Invited Users">
    <%= if length(@user.invited_users) > 0 do %>
    <ul>
      <%= for invitee <- @user.invited_users do %>
        <li><%= link invitee.username, to: Routes.user_path(@conn, :show, invitee.id) %></li>
      <% end %>
    </ul>
    <% else %>
      No one yet...
    <% end %>
  </section>

  <div class="row">
    <section class="col col-50 card" data-title="Posts">
      <%= render KnowhereCafeWeb.PostView, "posts_table.html", conn: @conn, posts: @user.posts %>
    </section>
    <section class="col col-50 card" data-title="Statuses">
      <%= render KnowhereCafeWeb.StatusView, "statuses_table.html", conn: @conn, statuses: @user.statuses %>
    </section>
  </div>
</article>