lib/knowhere_cafe_web/router.ex
defmodule KnowhereCafeWeb.Router do
  use KnowhereCafeWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowInvitation]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {KnowhereCafeWeb.LayoutView, :not_auth}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler

    plug :put_layout, {KnowhereCafeWeb.LayoutView, :app}
  end

  scope "/" do
    pipe_through :browser

    # Session only (no registration) and extension routes for Pow
    pow_session_routes()
    pow_extension_routes()
  end

  scope "/", KnowhereCafeWeb do
    pipe_through :browser

    get "/about", PageController, :about
  end

  scope "/", Pow.Phoenix, as: "pow" do
    # Registration was disabled so pow_routes() was replaced with
    # pow_session_routes() which means that this is needed to handle the routes.
    pipe_through [:browser, :protected]

    resources "/registration", RegistrationController,
      singleton: true,
      only: [:edit, :update]
  end

  scope "/", KnowhereCafeWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index

    resources "/statuses", StatusController, except: [:new, :update, :edit, :delete]
    resources "/posts", PostController, except: [:update, :edit, :delete]
    resources "/tags", TagController, except: [:new, :update, :edit, :delete]

    post "/statuses/:status_id/thanks/", ThanksController, :create_status_thanks
    post "/posts/:post_id/thanks", ThanksController, :create_post_thanks
    post "/comments/:comment_id/thanks", ThanksController, :create_comment_thanks

    post "/posts/:post_id/comment", CommentController, :create

    get "/users", UserController, :index
    get "/users/:id", UserController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", KnowhereCafeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: KnowhereCafeWeb.Telemetry
    end
  end
end

lib/knowhere_cafe_web/views/layout_view.ex
defmodule KnowhereCafeWeb.LayoutView do
  use KnowhereCafeWeb, :view
end

lib/knowhere_cafe_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "head.html", assigns %>
  <body>
    <div id="rainbox" class="rain"></div>
    <div class="row row-stretch gapless">

      <div class="col col-20">
      <nav>
        <a href="/" class="w-100">
          <img class="logo" src="<%= Routes.static_path(@conn, "/images/logo.svg") %>" alt="Knowhere Cafe"/>
          <h1 class="gapless">Knowhere Cafe</h1>
        </a>

        <a href="<%= Routes.user_path(@conn, :index) %>", class="w-100">
          <i class="gg-user-list"></i> Users
        </a>
        <a href="<%= Routes.post_path(@conn, :index) %>", class="w-100">
          <i class="gg-list"></i> Posts
        </a>
        <a href="<%= Routes.status_path(@conn, :index) %>", class="w-100">
          <i class="gg-attachment"></i> Statuses
        </a>
        <a href="<%= Routes.tag_path(@conn, :index) %>", class="w-100">
          <i class="gg-tag"></i> Tags
        </a>

        <%# The LiveDashboard is only shown in dev mode %>
        <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
          <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "w-100" %>
        <% end %>

        <%= render "flash.html", assigns %>
      </nav>
      </div>


      <div class="col col-80">
        <main role="main" class="row row-stretch">
          <%= @inner_content %>
        </main>
      </div>
    </div>

    <div class="spacer"></div>

    <%= render "footer.html", assigns %>
  </body>
</html>

lib/knowhere_cafe_web/templates/layout/flash.html.eex
<%= cond do %>
  <% get_flash(@conn, :info) -> %>
    <p class="alert alert-info card primary" role="alert"><%= get_flash(@conn, :info) %></p>
  <% get_flash(@conn, :error) -> %>
    <p class="alert alert-danger card secondary" role="alert"><%= get_flash(@conn, :error) %></p>
  <% true -> %>
    <p></p>
<% end %>

lib/knowhere_cafe_web/templates/layout/footer.html.eex
<footer>
  <span>Knowhere Cafe &alpha; <%= Mix.Project.config[:version] %></span>
  <span>
    <%= length(Pow.Store.CredentialsCache.users([otp_app: :knowhere_cafe], KnowhereCafe.Users.User)) %>
    users online
  </span>
  <a href="https://sr.ht/~rushsteve1/knowhere_cafe" target="_blank">Source Code</a>
  <a href="javascript:void(0)" onclick="toggleRain()">Toggle Rain</a>

  <%= if assigns[:current_user] do %>
    <%= link "About", to: Routes.page_path(@conn, :about) %>

    <%= link "Sign Out", to: Routes.pow_session_path(@conn, :delete), method: :delete %>
  <% end %>
</footer>

lib/knowhere_cafe_web/templates/layout/head.html.eex
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Knowhere Cafe</title>
  <link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/images/apple-touch-icon.png") %>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicon-32x32.png") %>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicon-16x16.png") %>">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>

lib/knowhere_cafe_web/templates/layout/not_auth.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "head.html", assigns %>
  <body>
    <div id="rainbox" class="rain"></div>

    <main role="main" class="c">
      <noscript class="card">
        This site requires JavaScript for some functions, so things might break without it.
      </noscript>

      <a href="/" style="text-decoration: none;">
        <img class="logo" src="<%= Routes.static_path(@conn, "/images/logo.svg") %>">
        <h1>Knowhere Cafe</h1>
      </a>

      <%= @inner_content %>
      <%= render "flash.html", assigns %>
    </main>

    <div class="m-spacer"></div>

    <%= render "footer.html", assigns %>
  </body>
</html>