lib/knowhere_cafe_web/router.ex
defmodule KnowhereCafeWeb.Router do
  use KnowhereCafeWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowInvitation]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {KnowhereCafeWeb.LayoutView, :not_auth}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler

    plug :put_layout, {KnowhereCafeWeb.LayoutView, :app}
  end

  scope "/" do
    pipe_through :browser

    # Session only (no registration) and extension routes for Pow
    pow_session_routes()
    pow_extension_routes()
  end

  scope "/", KnowhereCafeWeb do
    pipe_through :browser

    get "/about", PageController, :about
  end

  scope "/", Pow.Phoenix, as: "pow" do
    # Registration was disabled so pow_routes() was replaced with
    # pow_session_routes() which means that this is needed to handle the routes.
    pipe_through [:browser, :protected]

    resources "/registration", RegistrationController,
      singleton: true,
      only: [:edit, :update]
  end

  scope "/", KnowhereCafeWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index

    resources "/statuses", StatusController, except: [:new, :update, :edit, :delete]
    resources "/posts", PostController, except: [:update, :edit, :delete]
    resources "/tags", TagController, except: [:new, :update, :edit, :delete]

    post "/statuses/:status_id/thanks/", ThanksController, :create_status_thanks
    post "/posts/:post_id/thanks", ThanksController, :create_post_thanks
    post "/comments/:comment_id/thanks", ThanksController, :create_comment_thanks

    post "/posts/:post_id/comment", CommentController, :create

    get "/users", UserController, :index
    get "/users/:id", UserController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", KnowhereCafeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: KnowhereCafeWeb.Telemetry
    end
  end
end

lib/knowhere_cafe/posts.ex
defmodule KnowhereCafe.Posts do
  @moduledoc """
  The Posts context.
  """

  import Ecto.Query, warn: false
  alias KnowhereCafe.Repo

  alias KnowhereCafe.Posts.Post

  @doc """
  Returns the list of posts. Can be limited.

  ## Examples

      iex> list_posts()
      [%Post{}, ...]

  """
  def list_posts do
    Repo.all(from p in Post, order_by: [desc: p.inserted_at])
    |> Repo.preload(:user)
  end

  def list_posts(limit) do
    Repo.all(from p in Post, limit: ^limit, order_by: [desc: p.inserted_at])
    |> Repo.preload(:user)
  end

  @doc """
  Gets a single post.

  Raises `Ecto.NoResultsError` if the Post does not exist.

  ## Examples

      iex> get_post!(123)
      %Post{}

      iex> get_post!(456)
      ** (Ecto.NoResultsError)

  """
  def get_post!(id) do
    Post
    |> Repo.get!(id)
    |> Repo.preload([
      :user,
      :children,
      :tags,
      parent: [:user],
      comments: [:user],
      thanks: [:user]
    ])
  end

  @doc """
  Creates a post.

  ## Examples

      iex> create_post(%{field: value})
      {:ok, %Post{}}

      iex> create_post(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_post(attrs \\ %{}) do
    %Post{}
    |> Post.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a post.

  ## Examples

      iex> update_post(post, %{field: new_value})
      {:ok, %Post{}}

      iex> update_post(post, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_post(%Post{} = post, attrs) do
    post
    |> Post.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a post.

  ## Examples

      iex> delete_post(post)
      {:ok, %Post{}}

      iex> delete_post(post)
      {:error, %Ecto.Changeset{}}

  """
  def delete_post(%Post{} = post) do
    Repo.delete(post)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking post changes.

  ## Examples

      iex> change_post(post)
      %Ecto.Changeset{data: %Post{}}

  """
  def change_post(%Post{} = post, attrs \\ %{}) do
    Post.changeset(post, attrs)
  end

  @doc """
  Returns the list of posts belonging to a parent post.

  ## Examples

      iex> list_posts_on_parent()
      [%Post{}, ...]

  """
  def list_posts_on_parent(id) do
    Repo.all(from p in Post, where: p.post_id == ^id)
    |> Repo.preload(:user)
  end

  @doc """
  Returns a series of Posts, Comments, and Thanks associated with this post
  ordered by their insertion time. This forms a "timeline" of the activity
  around a post, which is the primary view of the post.

  ## Examples

      iex> post_timeline(%Post{})
      [%Post{}, %Comment{}, %Thanks{}, ...]

      iex> post_timeline(id)
      [%Post{}, %Comment{}, %Thanks{}, ...]

  """
  def post_timeline(%Post{:children => children, :comments => comments, :thanks => thanks}) do
    Enum.sort(
      children ++ comments ++ thanks,
      &(&1.inserted_at < &2.inserted_at)
    )
  end

  def get_post_timeline(id) do
    # Alternatively some kind of UNION query or something could likely
    # do what I want here. But I had issues with that, so this is easier.
    children = KnowhereCafe.Comments.list_comments_on_post(id)
    comments = list_posts_on_parent(id)
    thanks = KnowhereCafe.Thanks.list_thanks_on_post(id)

    Enum.sort(
      children ++ comments ++ thanks,
      &(NaiveDateTime.compare(&1.inserted_at, &2.inserted_at) == :lt)
    )
  end
end

lib/knowhere_cafe/posts/post.ex
defmodule KnowhereCafe.Posts.Post do
  use Ecto.Schema
  import Ecto.Changeset
  # Alias itself since the structure is self-referencing
  alias KnowhereCafe.Posts.Post
  alias KnowhereCafe.Users.User
  alias KnowhereCafe.Thanks
  alias KnowhereCafe.Comments.Comment
  alias KnowhereCafe.Tags

  schema "posts" do
    field :content, :string
    field :title, :string
    # field :user_id, :id
    # field :post_id, :id

    belongs_to :parent, Post, foreign_key: :post_id
    has_many :children, Post
    belongs_to :user, User
    has_many :thanks, Thanks.Post
    has_many :comments, Comment
    many_to_many :tags, Tags.Tag, join_through: "posts_tags", unique: true

    timestamps()
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:title, :content, :user_id, :post_id])
    |> validate_required([:title, :content, :user_id])
    |> put_assoc(:tags, Tags.get_many_tags(attrs["tags_ids"]))
    |> validate_length(:title, min: 2)
    |> validate_length(:title, max: 50)
    |> validate_length(:content, min: 2)
    |> validate_length(:content, max: 2000)
  end
end

lib/knowhere_cafe/thanks/post.ex
defmodule KnowhereCafe.Thanks.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias KnowhereCafe.Users.User
  alias KnowhereCafe.Posts.Post

  schema "post_thanks" do
    # field :post_id, :id
    # field :user_id, :id
    belongs_to :user, User
    belongs_to :post, Post

    timestamps()
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:user_id, :post_id])
    |> validate_required([:user_id, :post_id])
    |> unique_constraint([:user_id, :post_id])
  end
end

lib/knowhere_cafe_web/controllers/post_controller.ex
defmodule KnowhereCafeWeb.PostController do
  use KnowhereCafeWeb, :controller

  alias KnowhereCafe.Repo
  alias KnowhereCafe.Posts
  alias KnowhereCafe.Posts.Post
  alias KnowhereCafe.Tags

  def index(conn, _params) do
    posts = Posts.list_posts()
    render(conn, "index.html", posts: posts)
  end

  def new(conn, params) do
    changeset = Posts.change_post(%Post{})
    changeset = update_in(changeset.data, &Repo.preload(&1, :tags))
    parent = params["parent"]
    all_tags = Tags.list_tags()

    render(conn, "new.html",
      changeset: changeset,
      parent: parent,
      all_tags: all_tags
    )
  end

  def create(conn, %{"post" => post_params} = params) do
    post_params =
      post_params
      |> Map.put("user_id", conn.assigns.current_user.id)
      # Defaults to nil
      |> Map.put("post_id", params["parent"])

    case Posts.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html",
          changeset: update_in(changeset.data, &Repo.preload(&1, :tags)),
          parent: post_params["post_params"],
          all_tags: Tags.list_tags()
        )
    end
  end

  def show(conn, %{"id" => id}) do
    post = Posts.get_post!(id)
    timeline = Posts.get_post_timeline(id)
    render(conn, "show.html", post: post, timeline: timeline)
  end
end

lib/knowhere_cafe_web/views/post_view.ex
defmodule KnowhereCafeWeb.PostView do
  use KnowhereCafeWeb, :view

  alias KnowhereCafe.Posts.Post
  alias KnowhereCafe.Comments.Comment
  alias KnowhereCafe.Thanks

  # Renders an item in the timeline view based on what the struct type is.
  defp render_timeline_item(conn, %Post{} = post, index) do
    render("timeline_post.html", conn: conn, post: post, index: index)
  end

  defp render_timeline_item(conn, %Comment{} = comment, index) do
    render("timeline_comment.html", conn: conn, comment: comment, index: index)
  end

  defp render_timeline_item(conn, %Thanks.Post{} = thanks, index) do
    render("timeline_thanks.html", conn: conn, thanks: thanks, index: index)
  end

  defp render_timeline_item(_, _, _), do: nil
end

lib/knowhere_cafe_web/templates/post/index.html.eex
<section class="card col col-60" data-title="Posts">
  <%= link "New Post", to: Routes.post_path(@conn, :new), class: "btn" %>
  <hr/>

  <%= render "posts_table.html", conn: @conn, posts: @posts %>
</section>

lib/knowhere_cafe_web/templates/post/new.html.eex
<section class="c card w-100" data-title="New Post">
  <%= form_for @changeset, Routes.post_path(@conn, :create, parent: @parent), fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <div class="row">
      <div class="col col-75">
        <%= label f, :title %>
        <%= text_input f, :title, maxlength: 50, class: "card w-100", autocomplete: "off" %>
        <%= error_tag f, :title %>
      </div>

      <div class="col col-25">
        <%= label f, :tags %>
        <%= multiple_select f, :tags_ids, Enum.map(@all_tags, &{&1.name, &1.id}), class: "card w-100" %>
        <%= error_tag f, :tags_ids %>
      </div>
    </div>

    <%= label f, :content %>
    <%= textarea f, :content, class: "card w-100", rows: 5 %>
    <%= error_tag f, :content %>

    <div class="row">
      <%= submit "Submit Post", class: "btn w-100" %>
    </div>
  <% end %>
</section>

lib/knowhere_cafe_web/templates/post/posts_table.html.eex
<%= if length(@posts) > 0 do %>
  <table class="w-100">
    <%= for post <- @posts do %>
      <tr>
        <td>
          <%= link truncate(post.title), to: Routes.post_path(@conn, :show, post.id), class: "w-100" %>
        </td>
        <td>
          by <%= link post.user.username, to: Routes.user_path(@conn, :show, post.user.id) %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  Nothing yet...
<% end %>

lib/knowhere_cafe_web/templates/post/show.html.eex
<article class="col col-80">
  <section  class="card w-100" data-title="Post" id="top">
    <%= if @post.parent do %>
      <section>
        <strong>Parent Post:</strong>
        <%= link @post.parent.title, to: Routes.post_path(@conn, :show, @post.parent.id) %>
        by <%= link @post.parent.user.username, to: Routes.user_path(@conn, :show, @post.parent.user.id) %>
      </section>
    <% end %>

    <h2><%= @post.title %></h2>
    <div>
      By <%= link @post.user.username, to: Routes.user_path(@conn, :show, @post.user.id) %>
      at <%= @post.inserted_at %>
    </div>

    <%= render_markdown @post.content, card: true %>

    <div>
      <strong>Tags:</strong>
      <%= if length(@post.tags) > 0 do %>
        <%= for tag <- @post.tags do %>
          <%= link tag.name, to: Routes.tag_path(@conn, :show, tag.id), class: "chip", style: "background-color: #{tag.color};" %>
        <% end %>
      <% else %>
        No tags
      <% end %>
    </div>
        <%= link "Thank Post", to: Routes.thanks_path(@conn, :create_post_thanks, @post.id), method: :post, class: "btn" %>
        <%= link "Create Child Post", to: Routes.post_path(@conn, :new, parent: @post.id), class: "btn" %>
  </section>

  <section class="c">
    <%= if length(@timeline) > 0 do %>
      <%= for {item, i} <- Enum.with_index(@timeline) do %>
        <%= render_timeline_item @conn, item, i %>
      <% end %>
    <% else %>
      <div class="card">
        No one has interacted with this post yet...
        You could be the first!
      </div>
    <% end %>

    <section class="col card" data-title="New Comment" id="comment">
      <%= form_for @conn, Routes.comment_path(@conn, :create, @post.id), fn f -> %>
        <%= textarea f, :content, class: "card w-100", placeholder: "Comment Text", rows: 4 %>
        <%= error_tag f, :content %>
        <div>
          <%= submit "Add Comment", class: "btn" %>
        </div>
      <% end %>
    </section>
  </section>
</article>

<div class="m-hidden"></div>

<div class="card minimap">
  <div>
    <a href="#top" data-title="Top Post">
      <i class="gg-push-chevron-up-r"></i>
    </a>
  </div>
  <%= for {item, i} <- Enum.with_index(@timeline) do %>
    <div>
      <a href="#<%= i %>">
        <%= case item do %>
          <% %Post{} -> %>
            <i class="gg-list"></i>
          <% %Comment{} -> %>
            <i class="gg-comment"></i>
          <% %Thanks.Post{} -> %>
            <i class="gg-bell"></i>
        <% end %>
      </a>
    </div>
  <% end %>
  <div>
    <a href="#comment" data-title="New Comment">
      <i class="gg-add"></i>
    </a>
  </div>
</div>

lib/knowhere_cafe_web/templates/post/timeline_comment.html.eex
<section class="card" data-title="Comment" id="<%= @index %>">
  <%= render_markdown @comment.content %>
  <div>
    By <%= link @comment.user.username, to: Routes.user_path(@conn, :show, @comment.user.id) %>
    at <%= @comment.inserted_at %>
  </div>
  <%= link "Thank Comment", to: Routes.thanks_path(@conn, :create_comment_thanks, @comment.id) , method: :post, class: "btn" %>
</section>

<div style="margin: 0 3rem;">
  <%= for thanks <- @comment.thanks do %>
    <section class="card" data-title="Thanks">
      Comment thanked by
      <%= link thanks.user.username, to: Routes.user_path(@conn, :show, thanks.user.id) %>
      at <%= thanks.inserted_at %>
    </section>
  <% end %>
</div>

lib/knowhere_cafe_web/templates/post/timeline_post.html.eex
<section class="card" data-title="Post" id="<%= @index %>">
  <h4><%= link @post.title, to: Routes.post_path(@conn, :show, @post.id) %></h4>
  <div>
    By <%= link @post.user.username, to: Routes.user_path(@conn, :show, @post.user.id) %>
    at <%= @post.inserted_at %>
  </div>
</section>

lib/knowhere_cafe_web/templates/post/timeline_thanks.html.eex
<section class="card" data-title="Thanks" id="<%= @index %>">
  Post thanked by
  <%= link @thanks.user.username, to: Routes.user_path(@conn, :show, @thanks.user.id) %>
  at <%= @thanks.inserted_at %>
</section>